### ISSUE TITLE
Format converter for JsProtoUrl?

### ISSUE THREAD

**Issue by twitchyliquid64** [marin-m/pbtk#3]
Hi,

Wondering if you have a converter to go from the text proto url thingy that google uses, into an object in memory or JSON?

Ive been trying to do this myself, but are having some difficulty with the nested fields.

Good job with the XSS by the way. = )

**Comment by marin-m** [comment]
@twitchyliquid64 Hello,

Here's a general way to achieve this:
# Extract .proto structures from Google Maps using the "Step 1" option from the GUI (tip: not only web Google Maps call Google Maps' APIs, Earth has a desktop client, both have mobile clients...)
# Compile .proto's to your favourite language using matching bindings (docs [here](https://developers.google.com/protocol-buffers/docs/tutorials) for main ones)
# Serialize structures to URL through including [pburl_decoder.py](https://github.com/marin-m/pbtk/blob/master/utils/pburl_decoder.py) to your code if you're doing Python (if you need help porting the logic to another language I can help). proto_url_encode() just takes a message and returns a string.
I'm not uploading .proto structures here because copyright.

I don't think using JSON rather than manipulating Protobuf using language APIs is convenient, anyway if you want that there is a [standardized way](https://developers.google.com/protocol-buffers/docs/proto3#json) for this.

Have a good day

**Comment by marin-m** [comment]
>but are having some difficulty with the nested fields.

I've just moved some docs out of my local wiki: https://github.com/marin-m/pbtk/wiki/Protobuf-URL

The thing to know is that, for the "m" type, the integer value is the total number of subsequent “!”-separated blocks contained in the message. So, if there are three levels of nesting, you have the total number of inner "m" fields + every of their contained children as the topmost "m" value.

The following:
`!1m4!2m2!4i42!8sHi!9x65535`

Will evaluate to:
```
1 {
    2 {
        4 = 42
        8 = "Hi"
    }
    9 = 65535
}
```

**Comment by marin-m** [comment]
You can now use the `./utils/pburl_decoder.py` script individually, for the feature originally requested in this issue.

```
$ ./utils/pburl_decoder.py -h
usage: pburl_decoder.py [-h] pburl_data proto_file [proto_msg_name]

Decode a JsProtoUrl text message, providing a .proto.
```

It can be used as such:

```
$ ./utils/pburl_decoder.py '!1m4!1m3!1i0!2i0!3i0!2m0' ~/.pbtk/path/to/your.proto
region {
  tile {
    zoom: 0
    x: 0
    y: 0
  }
}
layer {
}
```

Don't forget to enclose URL data in simple quotes if your shell is bash.

**Comment by twitchyliquid64** [comment]
Thanks!! :D I shall use this when I get home

**Comment by jacano** [comment]
Hi marin-m, I'm wondering how did you get the JsProtoUrl proto file.
I tried your tool with googleearth_free.dll (Google Earth Windows client) and libearthmobile.so (Google Earth Android app) but none of them extracted the corresponding JsProtoUrl proto.

Any help on that, thanks!

**Comment by marin-m** [comment]
@jacano 

>and libearthmobile.so (Google Earth Android app)

It's the one I was thinking about. The https://www.google.com/maps/vt endpoint (serving tiles) has its requests defined by `maps/paint/proto/paint-request.proto` (serialized with JsProtoUrl) and its response, in the case of the binary Protobuf-based format, by `maps/paint/proto/client-vector-tile.proto`.

The https://www.google.com/maps endpoint (serving the frontend for the webapp) doesn't have its request definition embedded there, however you can use the Chrome-based extractor (Step 1) and rename fields on the go as you test and understand what they mean (Step 3).

**Comment by jacano** [comment]
Now I see, I got all those proto files but couldn't find the corresponding. TileCoordinateProto seems to be the one I'm looking for.

Thanks again marin-m and keep up the good work on this tool 👍

**Comment by marin-m** [comment]
You're welcome, the one you are looking for is more likely PaintRequest from `maps/paint/proto/paint-request.proto` (that comprises TileCoordinateProto from `maps/util/tile_coordinate.proto`, which stores only coordinates and zoom, as a nested message).

**Comment by jacano** [comment]
Yes, you are right. It is `maps/paint/proto/paint-request.proto`
I just wanted to find something that sounds familiar to me in those proto, that's why TileCoordinateProto opened my eyes.

I hope to have some time to encode a complete request to the endpoint you told me and decode some responses.
